import { FirmConfig, FirmKey } from "@/types";

export const FIRM_CONFIGS: Record<FirmKey, FirmConfig> = {
  mckinsey: {
    name: "McKinsey & Company",
    style: "hypothesis-driven, structured, MECE frameworks",
    tone: "formal, demanding, expects precise structure",
    evaluationWeights: {
      structure: 30,
      problemSolving: 25,
      quantitative: 25,
      communication: 10,
      creativity: 10,
    },
    feedbackTone: "Direct and data-driven. References McKinsey problem-solving approach.",
    color: "#003366",
  },
  bain: {
    name: "Bain & Company",
    style: "practical, results-oriented, answer-first",
    tone: "collaborative but rigorous, loves the so-what",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 20,
      communication: 20,
      creativity: 10,
    },
    feedbackTone: "Practical and direct. Focuses on real-world applicability.",
    color: "#CC0000",
  },
  bcg: {
    name: "Boston Consulting Group",
    style: "conceptual, creative, system-level thinking",
    tone: "intellectually curious, rewards unconventional insights",
    evaluationWeights: {
      structure: 20,
      problemSolving: 25,
      quantitative: 20,
      communication: 15,
      creativity: 20,
    },
    feedbackTone: "Conceptual and forward-looking. Rewards strategic creativity.",
    color: "#009A44",
  },
  ey: {
    name: "EY-Parthenon",
    style: "analytical, detail-oriented, evidence-based",
    tone: "methodical, expects thorough analysis",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 30,
      communication: 10,
      creativity: 10,
    },
    feedbackTone: "Analytical and precise. Focuses on evidence and data.",
    color: "#FFE600",
  },
  deloitte: {
    name: "Deloitte",
    style: "broad, industry-focused, implementation-heavy",
    tone: "practical, client-focused, values execution",
    evaluationWeights: {
      structure: 20,
      problemSolving: 25,
      quantitative: 20,
      communication: 20,
      creativity: 15,
    },
    feedbackTone: "Implementation-focused. Values practical recommendations.",
    color: "#86BC25",
  },
  kpmg: {
    name: "KPMG",
    style: "risk-aware, compliance-conscious, structured",
    tone: "methodical, risk-focused, expects thoroughness",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 25,
      communication: 15,
      creativity: 10,
    },
    feedbackTone: "Risk-conscious and thorough. Values comprehensive analysis.",
    color: "#00338D",
  },
  pwc: {
    name: "PwC Strategy&",
    style: "integrated, transformation-focused, digital-savvy",
    tone: "collaborative, forward-thinking, values innovation",
    evaluationWeights: {
      structure: 20,
      problemSolving: 25,
      quantitative: 20,
      communication: 20,
      creativity: 15,
    },
    feedbackTone: "Transformation-focused. Values digital and innovation thinking.",
    color: "#D04A02",
  },
  rolandberger: {
    name: "Roland Berger",
    style: "european, entrepreneurial, independent thinking",
    tone: "direct, values original thought, less rigid structure",
    evaluationWeights: {
      structure: 20,
      problemSolving: 30,
      quantitative: 20,
      communication: 15,
      creativity: 15,
    },
    feedbackTone: "Entrepreneurial and direct. Values independent strategic thinking.",
    color: "#0F4C81",
  },
  accenture: {
    name: "Accenture Strategy",
    style: "tech-forward, implementation-focused, data-driven",
    tone: "practical, digital-first, values scalability",
    evaluationWeights: {
      structure: 20,
      problemSolving: 25,
      quantitative: 25,
      communication: 15,
      creativity: 15,
    },
    feedbackTone: "Tech-forward and practical. Values digital transformation thinking.",
    color: "#A100FF",
  },
  oliver_wyman: {
    name: "Oliver Wyman",
    style: "industry-specialized, quantitative, risk-focused",
    tone: "precise, analytical, expects deep industry knowledge",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 30,
      communication: 10,
      creativity: 10,
    },
    feedbackTone: "Quantitative and industry-specific. Expects depth over breadth.",
    color: "#E4002B",
  },
  at_kearney: {
    name: "Kearney",
    style: "operations-focused, pragmatic, action-oriented",
    tone: "direct, values implementable solutions",
    evaluationWeights: {
      structure: 20,
      problemSolving: 30,
      quantitative: 20,
      communication: 20,
      creativity: 10,
    },
    feedbackTone: "Operations-focused and pragmatic. Values concrete action plans.",
    color: "#00A3E0",
  },
  lek: {
    name: "L.E.K. Consulting",
    style: "private equity focused, rigorous, data-intensive",
    tone: "sharp, expects tight logic and clean analytics",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 35,
      communication: 10,
      creativity: 5,
    },
    feedbackTone: "Rigorous and data-intensive. Expects PE-grade analytical precision.",
    color: "#1D3557",
  },
  monitor_deloitte: {
    name: "Monitor Deloitte",
    style: "strategy-focused, customer-centric, growth-oriented",
    tone: "thoughtful, values customer insight and market strategy",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 20,
      communication: 20,
      creativity: 10,
    },
    feedbackTone: "Strategy and growth focused. Values customer and market insight.",
    color: "#86BC25",
  },
  ibm_consulting: {
    name: "IBM Consulting",
    style: "tech-integration, AI-forward, enterprise-scale",
    tone: "systematic, values technology-driven transformation",
    evaluationWeights: {
      structure: 20,
      problemSolving: 25,
      quantitative: 25,
      communication: 15,
      creativity: 15,
    },
    feedbackTone: "Technology-forward. Values AI and enterprise transformation thinking.",
    color: "#0530AD",
  },
  strategy_and: {
    name: "Strategy& (PwC)",
    style: "distinctive thinking, identity-driven strategy",
    tone: "conceptual, challenges assumptions, values bold strategy",
    evaluationWeights: {
      structure: 20,
      problemSolving: 30,
      quantitative: 15,
      communication: 20,
      creativity: 15,
    },
    feedbackTone: "Bold and conceptual. Rewards distinctive strategic positioning.",
    color: "#D04A02",
  },
  huron: {
    name: "Huron Consulting",
    style: "sector-specialized, healthcare and education focused",
    tone: "practical, sector-aware, values domain expertise",
    evaluationWeights: {
      structure: 25,
      problemSolving: 25,
      quantitative: 20,
      communication: 20,
      creativity: 10,
    },
    feedbackTone: "Sector-specific and practical. Values deep domain knowledge.",
    color: "#00558C",
  },
};