"use client";

import { useRouter } from "next/navigation";
import { useSession, signOut } from "next-auth/react";
import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence, useScroll, useTransform } from "framer-motion";
import { ArrowRight, History, Settings, HelpCircle, MessageSquare, Mail } from "lucide-react";
import { Reveal } from "@/components/ui/reveal";

const FEATURES = [
  { img: "/homepage/blob-lavender.png", title: "Firm-specific feedback", copy: "Graded the way McKinsey, Bain, and BCG actually evaluate candidates. Each firm has its own rubric." },
  { img: "/homepage/blob-peach.png", title: "Realistic interviewer", copy: "An interviewer that never gives away answers. It pushes back, asks follow-ups, and holds a high bar." },
  { img: "/homepage/blob-mint.png", title: "Detailed scorecard", copy: "Structure, quantitative accuracy, communication. Each dimension scored and benchmarked against top candidates." },
  { img: "/homepage/blob-voice.png", title: "Voice + text", copy: "Practice speaking out loud or typing your answers. Both modes replicate real interview conditions." },
  { img: "/homepage/blob-pink.png", title: "Model answers", copy: "After each case, see exactly what the strongest candidates would have said differently." },
  { img: "/homepage/blob-yellow.png", title: "Performance tracking", copy: "Every session is saved. Track your score over time and see where you keep losing points." },
];

interface FadeImgProps {
  src: string;
  alt: string;
  style: React.CSSProperties;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  animate: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  transition: any;
  fetchPriority?: "high" | "low" | "auto";
}

function FadeImg({ src, alt, style, animate, transition, fetchPriority }: FadeImgProps) {
  const [loaded, setLoaded] = useState(false);
  const imgRef = useRef<HTMLImageElement>(null);

  // Cached images can finish loading before React attaches the onLoad
  // listener, so the load event never fires — check .complete on mount too.
  useEffect(() => {
    if (imgRef.current?.complete) setLoaded(true);
  }, []);

  return (
    <motion.img
      ref={imgRef}
      src={src}
      alt={alt}
      fetchPriority={fetchPriority}
      onLoad={() => setLoaded(true)}
      style={{ ...style, opacity: loaded ? style.opacity ?? 1 : 0, transition: "opacity 0.5s ease-out" }}
      animate={animate}
      transition={transition}
    />
  );
}

function Diamond({ style }: { style?: React.CSSProperties }) {
  return (
    <svg viewBox="0 0 24 24" style={{ width: "1.25rem", height: "1.25rem", ...style }} fill="currentColor">
      <path d="M12 2L22 12L12 22L2 12Z" />
    </svg>
  );
}

function Cross({ style }: { style?: React.CSSProperties }) {
  return (
    <svg viewBox="0 0 24 24" style={{ width: "1.25rem", height: "1.25rem", ...style }} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
      <line x1="12" y1="4" x2="12" y2="20" />
      <line x1="4" y1="12" x2="20" y2="12" />
    </svg>
  );
}

function Dot({ style }: { style?: React.CSSProperties }) {
  return (
    <svg viewBox="0 0 8 8" style={{ width: "0.5rem", height: "0.5rem", ...style }} fill="currentColor">
      <circle cx="4" cy="4" r="4" />
    </svg>
  );
}

function smoothScrollTo(id: string) {
  const el = document.getElementById(id);
  if (el) el.scrollIntoView({ behavior: "smooth" });
}

function TermsModal({ onClose }: { onClose: () => void }) {
  useEffect(() => {
    function h(e: KeyboardEvent) { if (e.key === "Escape") onClose(); }
    document.addEventListener("keydown", h);
    return () => document.removeEventListener("keydown", h);
  }, [onClose]);

  const cards = [
    { title: "1. Use of the service", body: "MyCasePrep is a case interview practice platform. You agree to use the app only for lawful purposes consistent with its intended use. You must not attempt to reverse engineer, scrape, or abuse the platform." },
    { title: "2. AI-generated content", body: "Feedback and scores are generated by an AI model for educational and practice purposes only. They do not constitute professional career advice. Results may vary and are not a guarantee of performance in real interviews." },
    { title: "3. Account responsibility", body: "You are responsible for maintaining the security of your account credentials. MyCasePrep reserves the right to suspend or terminate accounts that violate these terms." },
    { title: "4. Disclaimers & limitation of liability", body: 'The app is provided "as is" without warranties of any kind. In no event shall MyCasePrep be liable for any indirect, incidental, or consequential damages, including loss of profits or data.' },
    { title: "5. Contact", body: "For questions about these terms contact me at seho.vince@gmail.com." },
  ];

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      onClick={onClose}
      style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", zIndex: 500, display: "flex", alignItems: "center", justifyContent: "center", padding: "1.5rem" }}
    >
      <motion.div
        initial={{ opacity: 0, y: 24, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 24, scale: 0.97 }} transition={{ duration: 0.2 }}
        onClick={e => e.stopPropagation()}
        style={{ background: "white", borderRadius: "18px", maxWidth: "580px", width: "100%", maxHeight: "82vh", overflow: "hidden", display: "flex", flexDirection: "column", boxShadow: "0 24px 64px rgba(0,0,0,0.2)" }}
      >
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: "1px solid var(--hp-border)", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <div style={{ fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--hp-soft-foreground)", marginBottom: "3px" }}>Legal</div>
            <h2 style={{ fontSize: "1.2rem", fontWeight: 700, color: "var(--hp-foreground)", margin: 0 }}>Terms & conditions</h2>
            <div style={{ fontSize: "0.75rem", color: "var(--hp-soft-foreground)", marginTop: "2px" }}>Last updated: June 26, 2026</div>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", color: "var(--hp-soft-foreground)", fontSize: "1.3rem", lineHeight: 1, padding: "0.25rem", marginLeft: "1rem" }}>✕</button>
        </div>
        <div style={{ overflowY: "auto", padding: "1.25rem 1.75rem", display: "flex", flexDirection: "column", gap: "0.75rem" }}>
          {cards.map(c => (
            <div key={c.title} style={{ background: "var(--hp-primary-soft)", borderRadius: "10px", padding: "1rem 1.25rem", border: "1px solid var(--hp-border)" }}>
              <div style={{ fontWeight: 700, fontSize: "0.875rem", color: "var(--hp-foreground)", marginBottom: "0.4rem" }}>{c.title}</div>
              <p style={{ fontSize: "0.85rem", color: "var(--hp-soft-foreground)", lineHeight: 1.7, margin: 0 }}>{c.body}</p>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}

function ProfileDropdown({ user, onClose }: { user: { name?: string | null; email?: string | null; image?: string | null }; onClose: () => void }) {
  const router = useRouter();
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    function h(e: MouseEvent) { if (ref.current && !ref.current.contains(e.target as Node)) onClose(); }
    document.addEventListener("mousedown", h);
    return () => document.removeEventListener("mousedown", h);
  }, [onClose]);

  const item = (icon: React.ReactNode, label: string, onClick: () => void, danger?: boolean) => (
    <button onClick={onClick}
      style={{ width: "100%", display: "flex", alignItems: "center", gap: "0.75rem", padding: "0.6rem 1rem", background: "none", border: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", fontSize: "0.875rem", fontWeight: 500, color: danger ? "#dc2626" : "var(--hp-foreground)", textAlign: "left", transition: "background 0.1s" }}
      onMouseEnter={e => (e.currentTarget.style.background = "var(--hp-primary-soft)")}
      onMouseLeave={e => (e.currentTarget.style.background = "none")}
    >
      <span style={{ color: danger ? "#dc2626" : "var(--hp-soft-foreground)", flexShrink: 0 }}>{icon}</span>
      {label}
    </button>
  );

  return (
    <div ref={ref} style={{ position: "relative" }}>
      <AnimatePresence>
        <motion.div
          initial={{ opacity: 0, y: 8, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8, scale: 0.96 }} transition={{ duration: 0.15 }}
          style={{ position: "absolute", top: "calc(100% + 10px)", right: 0, width: "240px", background: "white", borderRadius: "14px", border: "1px solid var(--hp-border)", boxShadow: "0 8px 32px oklch(0.4 0.05 280 / 14%)", overflow: "hidden", zIndex: 300 }}
        >
          <div style={{ padding: "1rem 1rem 0.75rem", borderBottom: "1px solid var(--hp-border)", display: "flex", alignItems: "center", gap: "0.75rem" }}>
            {user.image
              ? <img src={user.image} alt="" style={{ width: 40, height: 40, borderRadius: "9999px", objectFit: "cover", flexShrink: 0 }} />
              : <div style={{ width: 40, height: 40, borderRadius: "9999px", background: "var(--hp-primary)", color: "white", display: "grid", placeItems: "center", fontWeight: 700, flexShrink: 0 }}>{(user.name ?? user.email ?? "?").charAt(0).toUpperCase()}</div>
            }
            <div style={{ minWidth: 0 }}>
              <div style={{ fontWeight: 600, fontSize: "0.9rem", color: "var(--hp-foreground)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{user.name ?? "User"}</div>
              <div style={{ fontSize: "0.75rem", color: "var(--hp-soft-foreground)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{user.email}</div>
            </div>
          </div>
          <div style={{ padding: "0.5rem" }}>
            {item(<History size={16} />, "History", () => { router.push("/history"); onClose(); })}
            {item(<Settings size={16} />, "Settings", () => { router.push("/settings"); onClose(); })}
          </div>
          <div style={{ borderTop: "1px solid var(--hp-border)", padding: "0.5rem" }}>
            {item(<HelpCircle size={16} />, "Help", () => {})}
            {item(<MessageSquare size={16} />, "Send feedback", () => {})}
          </div>
          <div style={{ borderTop: "1px solid var(--hp-border)", padding: "0.5rem" }}>
            {item(
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" /><polyline points="16 17 21 12 16 7" /><line x1="21" y1="12" x2="9" y2="12" /></svg>,
              "Sign out", () => { signOut({ callbackUrl: "/" }); onClose(); }, true
            )}
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}

export default function LandingPage() {
  const router = useRouter();
  const { data: session, status } = useSession();
  const loading = status === "loading";
  const user = session?.user;
  const cta = user ? "/dashboard" : "/auth";
  const [profileOpen, setProfileOpen] = useState(false);
  const [showTerms, setShowTerms] = useState(false);

  const { scrollY } = useScroll();
  const navBg            = useTransform(scrollY, [0, 180], ["oklch(0.97 0.03 290 / 0)", "oklch(0.97 0.03 290 / 0.92)"]);
  const navBlur          = useTransform(scrollY, [0, 180], ["blur(0px)", "blur(16px)"]);
  const navBorderOpacity = useTransform(scrollY, [0, 180], [0, 1]);

  const BTN_H = "38px";
  const FONT  = "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif";

  const textLink: React.CSSProperties = {
    background: "none", border: "none", fontSize: "0.875rem", fontWeight: 500,
    color: "var(--hp-soft-foreground)", cursor: "pointer", padding: "0 0.5rem",
    fontFamily: FONT, display: "inline-flex", alignItems: "center",
    height: BTN_H, lineHeight: "1", transition: "color 0.15s",
  };

  const pillWhite: React.CSSProperties = {
    height: BTN_H, padding: "0 1.1rem", borderRadius: "9999px",
    border: "1px solid var(--hp-border-strong)", background: "rgba(255,255,255,0.78)",
    color: "var(--hp-foreground)", fontSize: "0.875rem", fontWeight: 600,
    cursor: "pointer", fontFamily: FONT, backdropFilter: "blur(8px)",
    display: "inline-flex", alignItems: "center", lineHeight: "1",
    whiteSpace: "nowrap", transition: "background 0.15s",
  };

  const pillPurple: React.CSSProperties = {
    height: BTN_H, padding: "0 1.25rem", borderRadius: "9999px",
    border: "none", background: "var(--hp-primary)", color: "var(--hp-primary-foreground)",
    fontSize: "0.875rem", fontWeight: 600, cursor: "pointer", fontFamily: FONT,
    display: "inline-flex", alignItems: "center", gap: "0.4rem",
    lineHeight: "1", whiteSpace: "nowrap",
    boxShadow: "0 2px 0 oklch(0.4 0.16 285)", transition: "opacity 0.15s",
  };

  return (
    <div style={{
      minHeight: "100vh", fontFamily: FONT,
      background: "var(--hp-bg)",
      backgroundImage: [
        "radial-gradient(at 8% 12%, var(--hp-lavender) 0px, transparent 45%)",
        "radial-gradient(at 92% 10%, var(--hp-peach) 0px, transparent 45%)",
        "radial-gradient(at 85% 92%, var(--hp-mint) 0px, transparent 50%)",
        "radial-gradient(at 10% 92%, var(--hp-sky) 0px, transparent 45%)",
      ].join(", "),
      backgroundAttachment: "fixed",
    }}>

      {/* Nav */}
      <motion.header style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "0.875rem 2.5rem", boxSizing: "border-box",
        backgroundColor: navBg, backdropFilter: navBlur,
      }}>
        <motion.div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: "1px", background: "var(--hp-border)", opacity: navBorderOpacity }} />

        <span onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          style={{ display: "inline-flex", alignItems: "center", gap: "0.3rem", fontWeight: 700, fontSize: "1.15rem", letterSpacing: "-0.02em", color: "var(--hp-foreground)", cursor: "pointer", flexShrink: 0, fontFamily: FONT }}>
          <img src="/newlogomcp.png" alt="" style={{ width: "26px", height: "26px", flexShrink: 0 }} />
          <span style={{ position: "relative", top: "-1px" }}>mycaseprep</span>
        </span>

        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <button style={textLink} onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--hp-foreground)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--hp-soft-foreground)")}>Home</button>

          <button style={textLink} onClick={() => smoothScrollTo("features")}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--hp-foreground)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--hp-soft-foreground)")}>Features</button>

          <button style={textLink} onClick={() => smoothScrollTo("privacy")}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--hp-foreground)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--hp-soft-foreground)")}>Privacy</button>

          <button
            onClick={() => router.push(user ? "/library" : "/auth")}
            style={textLink}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--hp-foreground)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--hp-soft-foreground)")}
          >Library</button>

          <button
            onClick={() => router.push("/guide")}
            style={textLink}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--hp-foreground)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--hp-soft-foreground)")}
          >Guide</button>

          <button style={pillPurple} onClick={() => router.push(cta)}
            onMouseEnter={e => (e.currentTarget.style.opacity = "0.88")}
            onMouseLeave={e => (e.currentTarget.style.opacity = "1")}>
            {user ? "Start practicing" : "Get started"}
            <ArrowRight size={15} />
          </button>

          {!loading && (!user ? (
            <button style={pillWhite} onClick={() => router.push("/auth")}
              onMouseEnter={e => (e.currentTarget.style.background = "rgba(255,255,255,0.96)")}
              onMouseLeave={e => (e.currentTarget.style.background = "rgba(255,255,255,0.78)")}>Sign in</button>
          ) : (
            <div style={{ position: "relative" }}>
              <button onClick={() => setProfileOpen(o => !o)} style={{ width: BTN_H, height: BTN_H, borderRadius: "9999px", border: "2px solid var(--hp-primary)", padding: 0, cursor: "pointer", background: "var(--hp-primary)", overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center" }}>
                {user.image
                  ? <img src={user.image} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                  : <span style={{ color: "white", fontWeight: 700, fontSize: "0.95rem", fontFamily: FONT }}>{(user.name ?? user.email ?? "?").charAt(0).toUpperCase()}</span>
                }
              </button>
              {profileOpen && <ProfileDropdown user={user} onClose={() => setProfileOpen(false)} />}
            </div>
          ))}
        </div>
      </motion.header>

      <div style={{ paddingTop: "60px" }}>
        <div style={{ maxWidth: "1280px", margin: "0 auto" }}>
          <style>{`
            .hp-hero-grid { display: grid; gap: 2.5rem; padding: 2rem 2.5rem 5rem; }
            @media (min-width: 1024px) { .hp-hero-grid { grid-template-columns: 1fr 1fr; align-items: center; padding-top: 3rem; padding-bottom: 7rem; } }
            .hp-features-grid { display: grid; gap: 2rem; grid-template-columns: repeat(3, 1fr); }
            @media (max-width: 900px) { .hp-features-grid { grid-template-columns: repeat(2, 1fr); } }
            @media (max-width: 580px) { .hp-features-grid { grid-template-columns: 1fr; } }
          `}</style>

          {/* Hero */}
          <section className="hp-hero-grid">
            <div style={{ position: "relative", zIndex: 10 }}>
              <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="hp-chip">
                <Dot style={{ color: "var(--hp-primary)" }} />
                <span style={{ textTransform: "uppercase", letterSpacing: "0.08em", fontSize: "0.7rem" }}>Beta</span>
              </motion.div>

              <h1 style={{ marginTop: "1.25rem", fontSize: "clamp(2.75rem, 6vw, 5.5rem)", lineHeight: 1.05, letterSpacing: "-0.025em", fontWeight: 800, color: "var(--hp-foreground)", fontFamily: FONT }}>
                <motion.span initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} style={{ display: "block" }}>
                  Ace your
                </motion.span>
                <motion.span initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.05 }} style={{ display: "block" }}>
                  consulting case
                </motion.span>
                <motion.span initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.1 }} style={{ display: "block", color: "var(--hp-primary)" }}>
                  interview
                </motion.span>
              </h1>

              <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }}
                style={{ marginTop: "1.5rem", maxWidth: "28rem", fontSize: "1.05rem", color: "var(--hp-soft-foreground)", lineHeight: 1.65, fontWeight: 400 }}>
                Practice with a realistic interviewer simulation. Firm-specific scoring from MBB, Big 4, and 10+ leading consulting firms.
              </motion.p>

              <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} style={{ marginTop: "2rem" }}>
                <button className="hp-btn-primary hp-btn-lg" onClick={() => router.push(cta)} style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem", fontFamily: FONT, fontWeight: 600 }}>
                  {user ? "Open dashboard" : "Get started free"}
                  <ArrowRight size={18} />
                </button>
              </motion.div>
            </div>

            <div style={{ position: "relative" }}>
              <motion.div aria-hidden style={{ position: "absolute", inset: "2.5rem", zIndex: 0, background: "var(--hp-lavender)", opacity: 0.65, borderRadius: "60% 40% 50% 50% / 50% 60% 40% 50%" }}
                animate={{ borderRadius: ["60% 40% 50% 50% / 50% 60% 40% 50%", "40% 60% 60% 40% / 60% 30% 70% 40%", "60% 40% 50% 50% / 50% 60% 40% 50%"] }}
                transition={{ duration: 12, repeat: Infinity, ease: "easeInOut" }}
              />
              <FadeImg src="/homepage/hero-3d.png" alt="" fetchPriority="high"
                style={{ position: "relative", zIndex: 1, width: "100%", maxWidth: "32rem", margin: "0 auto", display: "block" }}
                animate={{ y: [0, -14, 0] }} transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
              />
              <motion.div style={{ position: "absolute", right: "1rem", top: "1.5rem", zIndex: 2, color: "var(--hp-primary)" }}
                animate={{ rotate: [0, 45, 0] }} transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}>
                <Diamond style={{ width: "1.5rem", height: "1.5rem", opacity: 0.7 }} />
              </motion.div>
              <motion.div style={{ position: "absolute", left: "0.5rem", bottom: "2.5rem", zIndex: 2, color: "var(--hp-primary)" }}
                animate={{ scale: [1, 1.2, 1] }} transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}>
                <Cross style={{ width: "1.25rem", height: "1.25rem", opacity: 0.5 }} />
              </motion.div>
            </div>
          </section>

          {/* Features */}
          <section id="features" style={{ padding: "5rem 2.5rem" }}>
            <Reveal>
              <div style={{ maxWidth: "40rem", margin: "0 auto", textAlign: "center" }}>
                <div className="hp-chip" style={{ display: "inline-flex", marginBottom: "1rem", gap: "0.4rem" }}>
                  <Dot style={{ color: "var(--hp-primary)" }} />
                  <span style={{ fontSize: "0.75rem", fontWeight: 600 }}>Features</span>
                </div>
                <h2 style={{ fontSize: "clamp(1.75rem, 4vw, 3rem)", letterSpacing: "-0.02em", fontWeight: 800, color: "var(--hp-foreground)", fontFamily: FONT }}>
                  Built for <span style={{ color: "var(--hp-primary)" }}>serious prep</span>
                </h2>
              </div>
            </Reveal>

            <div className="hp-features-grid" style={{ marginTop: "3.5rem" }}>
              {FEATURES.map((f, i) => (
                <Reveal key={f.title} delay={i * 0.07}>
                  <div className="hp-surface-card" style={{ position: "relative", padding: "1.75rem", height: "100%", boxSizing: "border-box" }}>
                    <div style={{ position: "absolute", top: "-1rem", right: "-1rem", width: "2.5rem", height: "2.5rem", display: "grid", placeItems: "center", borderRadius: "9999px", background: "var(--hp-primary)", color: "var(--hp-primary-foreground)", fontWeight: 700, fontSize: "0.875rem", boxShadow: "var(--hp-shadow-pop)", fontFamily: FONT }}>
                      {String(i + 1).padStart(2, "0")}
                    </div>
                    <FadeImg src={f.img} alt=""
                      style={{ display: "block", margin: "0 auto", width: "10rem", height: "10rem", objectFit: "contain" }}
                      animate={{ y: [0, -8, 0] }} transition={{ duration: 4 + (i % 3), repeat: Infinity, ease: "easeInOut" }}
                    />
                    <h3 style={{ marginTop: "1rem", fontSize: "1.1rem", fontWeight: 700, letterSpacing: "-0.01em", color: "var(--hp-foreground)", fontFamily: FONT }}>{f.title}</h3>
                    <p style={{ marginTop: "0.5rem", fontSize: "0.875rem", color: "var(--hp-soft-foreground)", lineHeight: 1.65 }}>{f.copy}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </section>

          {/* CTA */}
          <section style={{ padding: "0 2.5rem 4rem" }}>
            <Reveal>
              <div style={{ position: "relative", overflow: "hidden", borderRadius: "1.5rem", background: "var(--hp-primary)", padding: "4rem 2rem", textAlign: "center" }}>
                <motion.div style={{ position: "absolute", left: "2rem", top: "50%", transform: "translateY(-50%)", color: "oklch(0.99 0.005 95 / 20%)" }}
                  animate={{ rotate: [0, 45, 0] }} transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}>
                  <Diamond style={{ width: "4rem", height: "4rem" }} />
                </motion.div>
                <motion.div style={{ position: "absolute", right: "2rem", bottom: "1.5rem", color: "oklch(0.99 0.005 95 / 20%)" }}
                  animate={{ rotate: [0, 90, 0] }} transition={{ duration: 12, repeat: Infinity, ease: "easeInOut" }}>
                  <Diamond style={{ width: "2.5rem", height: "2.5rem" }} />
                </motion.div>
                <h2 style={{ fontSize: "clamp(1.75rem, 4vw, 3rem)", letterSpacing: "-0.02em", fontWeight: 800, color: "var(--hp-primary-foreground)", position: "relative", zIndex: 1, fontFamily: FONT }}>
                  Ready to ace your next case
                </h2>
                <p style={{ margin: "0.75rem auto 0", maxWidth: "28rem", color: "oklch(0.99 0.005 95 / 80%)", fontSize: "1rem", lineHeight: 1.6, position: "relative", zIndex: 1 }}>
                  Pick a firm. Pick a case. Start talking. I&apos;ll do the interviewing.
                </p>
                <div style={{ marginTop: "1.75rem", position: "relative", zIndex: 1 }}>
                  <button className="hp-btn-secondary hp-btn-lg" onClick={() => router.push(cta)} style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem", fontFamily: FONT, fontWeight: 600 }}>
                    {user ? "Open dashboard" : "Start practicing free"}
                    <ArrowRight size={18} />
                  </button>
                </div>
              </div>
            </Reveal>
          </section>

          {/* Privacy */}
          <section id="privacy" style={{ padding: "5rem 2.5rem 6rem" }}>
            <Reveal>
              <div style={{ maxWidth: "40rem", margin: "0 auto", textAlign: "center", marginBottom: "3rem" }}>
                <div className="hp-chip" style={{ display: "inline-flex", marginBottom: "1rem", gap: "0.4rem" }}>
                  <Dot style={{ color: "var(--hp-primary)" }} />
                  <span style={{ fontSize: "0.75rem", fontWeight: 600 }}>Privacy</span>
                </div>
                <h2 style={{ fontSize: "clamp(1.75rem, 4vw, 3rem)", letterSpacing: "-0.02em", fontWeight: 800, color: "var(--hp-foreground)", fontFamily: FONT }}>
                  Your <span style={{ color: "var(--hp-primary)" }}>data</span>. Your <span style={{ color: "var(--hp-primary)" }}>trust.</span>
                </h2>
                <p style={{ marginTop: "0.75rem", fontSize: "1rem", color: "var(--hp-soft-foreground)", lineHeight: 1.65 }}>
                  Simple and transparent. Here&apos;s exactly how MyCasePrep handles your information.
                </p>
              </div>
            </Reveal>

            <div style={{ maxWidth: "860px", margin: "0 auto", display: "grid", gap: "1rem" }}>
              {[
                { title: "Data we collect", body: "When you sign up, I collect your name and email to create your account. If you sign in with Google, I receive your name, email, and profile photo — I never see your Google password. Your case interview transcripts, scores, and performance history are stored to power your history and tracking features.", color: "var(--hp-lavender)" },
                { title: "Data sharing & security", body: "I do not sell, rent, or share your personal data with third parties for marketing purposes. Your interview transcripts are used only to generate your scorecard and are never shared publicly. I use industry-standard encryption in transit (HTTPS) and at rest.", color: "var(--hp-mint)" },
                { title: "Interview processing", body: "Your interview responses are processed by a scoring system to generate feedback and dimensional scores. I do not use your transcripts to train any models. Your responses are yours and remain private to your account.", color: "var(--hp-peach)" },
                { title: "Data deletion", body: "You may request deletion of your account and all associated data at any time by contacting me. Upon request, I will remove your account, transcripts, and personal information within 30 days.", color: "var(--hp-sky)" },
              ].map((card, i) => (
                <Reveal key={card.title} delay={i * 0.07}>
                  <div className="hp-surface-card" style={{ padding: "1.5rem 1.75rem", display: "flex", gap: "1.25rem", alignItems: "flex-start" }}>
                    <div style={{ width: "2.75rem", height: "2.75rem", borderRadius: "10px", background: card.color, flexShrink: 0, display: "grid", placeItems: "center" }}>
                      <Cross style={{ width: "1rem", height: "1rem", color: "var(--hp-foreground)", opacity: 0.5 }} />
                    </div>
                    <div>
                      <div style={{ fontWeight: 700, fontSize: "1rem", color: "var(--hp-foreground)", marginBottom: "0.4rem", fontFamily: FONT }}>{card.title}</div>
                      <p style={{ fontSize: "0.875rem", color: "var(--hp-soft-foreground)", lineHeight: 1.7, margin: 0 }}>{card.body}</p>
                    </div>
                  </div>
                </Reveal>
              ))}
            </div>

            <Reveal>
              <div style={{ maxWidth: "860px", margin: "1.5rem auto 0", textAlign: "center" }}>
                <p style={{ fontSize: "0.8rem", color: "var(--hp-soft-foreground)" }}>
                  Questions?{" "}
                  <a href="mailto:seho.vince@gmail.com" style={{ color: "var(--hp-primary)", fontWeight: 600, textDecoration: "none" }}>Email me</a>
                  {" "}· Last updated June 26, 2026
                </p>
              </div>
            </Reveal>
          </section>
        </div>

        {/* Footer */}
        <footer style={{ background: "oklch(0.16 0.02 280)", color: "oklch(0.75 0.02 280)", fontFamily: FONT }}>
          <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "3.5rem 2.5rem 2rem" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "2rem", paddingBottom: "2.5rem", borderBottom: "1px solid oklch(0.25 0.02 280)" }}>
              <div>
                <div style={{ display: "inline-flex", alignItems: "center", gap: "0.3rem", fontSize: "1.3rem", fontWeight: 700, color: "white", letterSpacing: "-0.02em", fontFamily: FONT }}>
                  <img src="/newlogomcp.png" alt="" style={{ width: "28px", height: "28px", flexShrink: 0 }} />
                  <span style={{ position: "relative", top: "-1px" }}>mycaseprep<span style={{ color: "var(--hp-primary)" }}>.</span></span>
                </div>
                <div style={{ marginTop: "0.5rem", fontSize: "0.8rem", color: "oklch(0.55 0.02 280)", textTransform: "uppercase", letterSpacing: "0.1em" }}>
                  © {new Date().getFullYear()} MyCasePrep. All rights reserved.
                </div>
              </div>
              <div style={{ display: "flex", gap: "2.5rem", flexWrap: "wrap" }}>
                <div>
                  <div style={{ fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "oklch(0.55 0.02 280)", marginBottom: "0.75rem" }}>Product</div>
                  <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                    {[
                      { label: "Features", action: () => smoothScrollTo("features") },
                      { label: "Library", action: () => router.push("/library") },
                      { label: "Guide", action: () => router.push("/guide") },
                      { label: "Start a case", action: () => router.push(cta) },
                    ].map(l => (
                      <button key={l.label} onClick={l.action}
                        style={{ background: "none", border: "none", color: "oklch(0.72 0.02 280)", fontSize: "0.875rem", cursor: "pointer", fontFamily: FONT, textAlign: "left", padding: 0, transition: "color 0.15s" }}
                        onMouseEnter={e => (e.currentTarget.style.color = "white")}
                        onMouseLeave={e => (e.currentTarget.style.color = "oklch(0.72 0.02 280)")}
                      >{l.label}</button>
                    ))}
                  </div>
                </div>
                <div>
                  <div style={{ fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "oklch(0.55 0.02 280)", marginBottom: "0.75rem" }}>Legal</div>
                  <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                    <button onClick={() => smoothScrollTo("privacy")}
                      style={{ background: "none", border: "none", color: "oklch(0.72 0.02 280)", fontSize: "0.875rem", cursor: "pointer", fontFamily: FONT, textAlign: "left", padding: 0, transition: "color 0.15s" }}
                      onMouseEnter={e => (e.currentTarget.style.color = "white")}
                      onMouseLeave={e => (e.currentTarget.style.color = "oklch(0.72 0.02 280)")}
                    >Privacy policy</button>
                    <button onClick={() => setShowTerms(true)}
                      style={{ background: "none", border: "none", color: "oklch(0.72 0.02 280)", fontSize: "0.875rem", cursor: "pointer", fontFamily: FONT, textAlign: "left", padding: 0, transition: "color 0.15s" }}
                      onMouseEnter={e => (e.currentTarget.style.color = "white")}
                      onMouseLeave={e => (e.currentTarget.style.color = "oklch(0.72 0.02 280)")}
                    >Terms & conditions</button>
                  </div>
                </div>
              </div>
            </div>
            <div style={{ paddingTop: "1.5rem", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "1rem" }}>
              <div style={{ fontSize: "0.75rem", color: "oklch(0.45 0.02 280)" }}>
                Built for serious candidates · Free to use · No credit card required
              </div>
              <div style={{ display: "flex", gap: "0.75rem" }}>
                {[
                  { icon: <Mail size={18} />, href: "mailto:seho.vince@gmail.com", label: "Email" },
                  { icon: <HelpCircle size={18} />, href: "#", label: "Help" },
                ].map(btn => (
                  <a key={btn.label} href={btn.href} title={btn.label}
                    style={{ width: "36px", height: "36px", borderRadius: "9999px", border: "1px solid oklch(0.28 0.02 280)", color: "oklch(0.65 0.02 280)", display: "flex", alignItems: "center", justifyContent: "center", textDecoration: "none", transition: "border-color 0.15s, color 0.15s" }}
                    onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = "var(--hp-primary)"; (e.currentTarget as HTMLElement).style.color = "white"; }}
                    onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.28 0.02 280)"; (e.currentTarget as HTMLElement).style.color = "oklch(0.65 0.02 280)"; }}
                  >{btn.icon}</a>
                ))}
              </div>
            </div>
          </div>
        </footer>
      </div>

      <AnimatePresence>
        {showTerms && <TermsModal onClose={() => setShowTerms(false)} />}
      </AnimatePresence>
    </div>
  );
}