"use client";

import { useEffect } from "react";
import { motion } from "framer-motion";

// Shared legal modal - used by the homepage footer and the auth form so the
// "terms and privacy policy" text is actually clickable in both places.
export default function TermsModal({ onClose }: { onClose: () => void }) {
  useEffect(() => {
    function h(e: KeyboardEvent) { if (e.key === "Escape") onClose(); }
    document.addEventListener("keydown", h);
    return () => document.removeEventListener("keydown", h);
  }, [onClose]);

  const cards = [
    { title: "1. Use of the service", body: "MyCasePrep is a case interview practice platform. You agree to use the app only for lawful purposes consistent with its intended use. You must not attempt to reverse engineer, scrape, or abuse the platform." },
    { title: "2. AI-generated content", body: "Feedback and scores are generated by an AI model for educational and practice purposes only. They do not constitute professional career advice. Results may vary and are not a guarantee of performance in real interviews." },
    { title: "3. Account responsibility", body: "You are responsible for maintaining the security of your account credentials. MyCasePrep reserves the right to suspend or terminate accounts that violate these terms." },
    { title: "4. Privacy & your data", body: "MyCasePrep collects your name and email to run your account, and stores your interview transcripts and scores to power your history. Your data is never sold or shared for marketing, and is never used to train models. You can export or permanently delete everything at any time from Settings." },
    { title: "5. Disclaimers & limitation of liability", body: 'The app is provided "as is" without warranties of any kind. In no event shall MyCasePrep be liable for any indirect, incidental, or consequential damages, including loss of profits or data.' },
    { title: "6. Contact", body: "For questions about these terms, reach out through the Help & feedback page, linked from any Help or Contact button in the app." },
  ];

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      onClick={onClose}
      style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", zIndex: 500, display: "flex", alignItems: "center", justifyContent: "center", padding: "1.5rem" }}
    >
      <motion.div
        role="dialog"
        aria-modal="true"
        aria-labelledby="terms-modal-title"
        initial={{ opacity: 0, y: 24, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 24, scale: 0.97 }} transition={{ duration: 0.2 }}
        onClick={e => e.stopPropagation()}
        style={{ background: "white", borderRadius: "18px", maxWidth: "580px", width: "100%", maxHeight: "82vh", overflow: "hidden", display: "flex", flexDirection: "column", boxShadow: "0 24px 64px rgba(0,0,0,0.2)", fontFamily: "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif" }}
      >
        <div style={{ padding: "1.5rem 1.75rem", borderBottom: "1px solid var(--hp-border)", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <div style={{ fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--hp-soft-foreground)", marginBottom: "3px" }}>Legal</div>
            <h2 id="terms-modal-title" style={{ fontSize: "1.2rem", fontWeight: 700, color: "var(--hp-foreground)", margin: 0 }}>Terms &amp; privacy</h2>
            <div style={{ fontSize: "0.75rem", color: "var(--hp-soft-foreground)", marginTop: "2px" }}>Last updated: June 26, 2026</div>
          </div>
          <button onClick={onClose} aria-label="Close terms and privacy dialog" style={{ background: "none", border: "none", cursor: "pointer", color: "var(--hp-soft-foreground)", fontSize: "1.3rem", lineHeight: 1, padding: "0.25rem", marginLeft: "1rem" }}>✕</button>
        </div>
        <div style={{ overflowY: "auto", padding: "1.25rem 1.75rem", display: "flex", flexDirection: "column", gap: "0.75rem" }}>
          {cards.map(c => (
            <div key={c.title} style={{ background: "var(--hp-primary-soft)", borderRadius: "10px", padding: "1rem 1.25rem", border: "1px solid var(--hp-border)" }}>
              <div style={{ fontWeight: 700, fontSize: "0.875rem", color: "var(--hp-foreground)", marginBottom: "0.4rem" }}>{c.title}</div>
              <p style={{ fontSize: "0.85rem", color: "var(--hp-soft-foreground)", lineHeight: 1.7, margin: 0 }}>{c.body}</p>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}
